vim.cmd[[autocmd FileType python nnoremap <buffer> <F8> :w \| sp \| hor resize 10 \| term python3 % <CR>]]
vim.cmd[[autocmd FileType python inoremap <buffer> <F8> <Esc> :w \| sp \| hor resize 10 \| term python3 % <CR>]]
vim.cmd[[autocmd FileType r nnoremap <buffer> <F8> :w \| Dispatch r  % <CR>]]
vim.cmd[[autocmd FileType r inoremap <buffer> <F8> <Esc> :w \| Dispatch r  % <CR>]]
vim.cmd[[autocmd FileType tex nnoremap <buffer> <F8> :w  <CR> :VimtexView <CR> ]]
vim.cmd[[autocmd FileType html nnoremap <buffer> <F8> :w  <CR>  ]]
vim.cmd[[autocmd FileType css nnoremap <buffer> <F8> :w  <CR>  ]]
vim.cmd[[autocmd FileType sh nnoremap <buffer> <F8> :w  \|sp \| hor resize 10 \| term ./% <CR>]]
vim.cmd[[autocmd FileType sh nnoremap <buffer> <F9> :w  \|sp \| hor resize 10 \| term ./% ]]

